image: Visual Studio 2017

build: off

environment:
    matrix:
    - SOLUTION_NAME: week2/task1/ThreadPoolTask/ThreadPoolTask.sln

before_build:
    - nuget restore %SOLUTION_NAME%

build_script:
    - msbuild %SOLUTION_NAME%

test:
    - dotnet test ~/week2/task1/ThreadPoolTask/ThreadPoolTests.csproj